imports:
    - { resource: tables.yml }

# Definición de variables/strings globales
parameters:
    nextgen.trackers.tables.prefix: 'phpbb_trackers_'

services:
    nextgen.trackers.functions:
        class: nextgen\trackers\functions
        arguments:
            - '@auth'
            - '@config'
            - '@service_container'
            - '@dbal.conn'
            - '@language'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '%core.php_ext%'
            - '%nextgen.trackers.tables.prefix%'

    nextgen.trackers.controller:
        class: nextgen\trackers\controller\main_controller
        arguments:
            - '@auth'
            - '@config'
            - '@content.visibility'
            - '@controller.helper'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@service_container'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%nextgen.trackers.tables.prefix%'

    nextgen.trackers.listener:
        class: nextgen\trackers\event\main_listener
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@controller.helper'
            - '@template'
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }

    nextgen.trackers.operator.viewtracker:
        class: nextgen\trackers\operators\viewtracker
        arguments:
            - '@config'
            - '@service_container'
            - '@language'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'

    nextgen.trackers.operator.viewproject:
        class: nextgen\trackers\operators\viewproject
        arguments:
            - '@config'
            - '@auth'
            - '@service_container'
            - '@language'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'

    nextgen.trackers.operator.viewticket:
        class: nextgen\trackers\operators\viewticket
        arguments:
            - '@config'
            - '@auth'
            - '@service_container'
            - '@language'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'

    nextgen.trackers.operator.statistics:
        class: nextgen\trackers\operators\statistics
        arguments:
            - '@config'
            - '@service_container'
            - '@dbal.conn'
            - '@language'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '@auth'
            - '%core.table_prefix%'

    nextgen.trackers.operator.posting:
        class: nextgen\trackers\operators\posting
        arguments:
            - '@auth'
            - '@service_container'
            - '@language'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '@files.upload'
            - '%core.table_prefix%'
            
    nextgen.trackers.notification.type.ticket_assigned:
        class: nextgen\trackers\notification\type\ticket_assigned
        shared: false
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_controller_helper, ['@controller.helper']]
        tags:
            - { name: notification.type }
            
    nextgen.trackers.notification.type.ticket_reply:
        class: nextgen\trackers\notification\type\ticket_reply
        shared: false
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_controller_helper, ['@controller.helper']]
        tags:
            - { name: notification.type }